command_timeout = 800

[directory]
fish_style_pwd_dir_length = 1

[username]
format = "[$user]($style) "

[hostname]
format = "[$hostname]($style) "

[localip]
disabled = true

[git_branch]
format = "[$symbol$branch]($style) "

[git_commit]
tag_disabled = false

[package]
disabled = true

# per-language configuration
[cmake]
format = "[$symbol $version]($style) "

[golang]
format = "[$symbol $version]($style) "

[gradle]
symbol = " "

[java]
format = "[${symbol} ${version}]($style) "

[kotlin]
symbol = "󱈙 "

[nodejs]
format = "[$symbol$version]($style) "

[python]
format = "[${symbol} ${pyenv_prefix}${version}( \\($virtualenv\\))]($style) "

[rust]
format = "[$symbol] ($style) "

[lua]
format = "[$symbol $version]($style) "
