[tools]
bat = "latest"
difftastic = "latest"
fd = "latest"
go = "latest"
jless = "latest"
neovim = "latest"
node = "lts"
"npm:biome" = "latest"
"npm:prettier" = "latest"
"pipx:ansible-core" = "latest"
"pipx:httpie" = "latest"
"pipx:pipenv" = "latest"
"pipx:poetry" = "latest"
"pipx:ruff" = "latest"
protoc = "latest"
python = "latest"
ripgrep = "latest"
rust = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
zellij = "latest"
zoxide = "latest"

[settings]
experimental = true
python_compile = false
go_set_gobin = false
idiomatic_version_file_enable_tools = []

[settings.pipx]
uvx = true

[settings.python]
uv_venv_auto = true
